name: phageannotate_env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - pip==23.3
  - python==3.11.4
  - pip:
      - biopython==1.81
      - joblib==1.2.0
      - numpy==1.24.3
      - pandas==1.5.3
      - propy3==1.1.1
      - scikit-learn==1.3.0
      - tqdm==4.65.0